### ISSUE TITLE
Add party manifesto (מצע) to application

### ISSUE THREAD

**Issue by shaybarak** [gardenofwine/Open-Knesset-Mobile#47]
A user request - to add the different party manifestos (מצע) somewhere in the application (user request).
The 18th knesset does not have the manifestos listed nicely like the 17th knesset:
http://www.knesset.gov.il/elections17/heb/list/ListIndex.asp
http://www.knesset.gov.il/elections18/heb/list/ListMenu.aspx
so it might be a manual job to get the manifesto data.

**Comment by ShaiMesisterano** [comment]
Solved at b7cd492341894ff78af6a80179290dc4399c2eed
