### ISSUE TITLE
הוספת מידע נוסף אודות מפלגות, כגון מצע המפלגות

### ISSUE THREAD

**Issue by gardenofwine** [gardenofwine/Open-Knesset-Mobile#5]
Add the party platform data
מצע
To the party page. The party page should be modified so that it has a button - "Platform" - that sends the user to a new page in the application, displaying that party’s platform.
Party platforms can be found here:
http://www.idi.org.il/elections_and_parties/Pages/elections_and_parties_main.aspx

**Comment by ShaiMesisterano** [comment]
Solved at b7cd492341894ff78af6a80179290dc4399c2eed
